name: modelwatch
version: '1.0.0'
config-version: 2
profile: modelwatch
model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]
models:
  modelwatch:
    staging:
      +materialized: view
    marts:
      +materialized: table
